// <auto-generated />
namespace BankAccountDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updated_BasicAcccount_AddedProperty_AccountType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updated_BasicAcccount_AddedProperty_AccountType));
        
        string IMigrationMetadata.Id
        {
            get { return "201503262055391_Updated_BasicAcccount_AddedProperty_AccountType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
